defaults:
  - dataset: ocean
  - experiment: base
  - imputer: zero_padder
  - model: ccvar
  - mixing: kgt
  - protocol: kstep
  - clustering: default
  - paths: local
  - _self_

hydra:
  job:
    chdir: false
