defaults:
  - dataset: ocean_cellular_dataset
  - ccdata: partial
  - experiment: base
  - imputer: dataholder
  - model: ccvarpartial
  - mixing: kgt
  - protocol: kstep
  - clustering: modularity
  - _self_

hydra:
  job:
    chdir: false
