defaults:
  - dataset: ocean_cellular_dataset
  - experiment: base
  - imputer: zeropadder
  - model: ccvar
  - mixing: kgt
  - protocol: kstep
  - clustering: default
  - paths: local
  - _self_

hydra:
  job:
    chdir: false
