defaults:
  - dataset: ocean_cellular_dataset
  - ccdata: partial
  - experiment: base
  - imputer: zeropadder
  - model: ccvar
  - mixing: kgt
  - protocol: kstep
  - clustering: default
  - _self_

hydra:
  job:
    chdir: false
